### ISSUE TITLE
To set request header

### ISSUE THREAD

**Issue by n04ln** [apptreesoftware/protoc-gen-twirp_dart#3]
Currently, request is set only `Content-Type` header.
So, I suggest a solution to set other header. (This solution is inspired by gRPC)

1. define CallOptions class (like following code) in https://github.com/apptreesoftware/twirp_dart_core
``` dart
class CallOptions {
	Map<String, String> headers;
	CallOptions() {
		headers = new Map<String, String>();
	}
	void setHeader(String key, String value) {
		headers[key] = value;
	}
}
```

2. call rpc method with `CallOptions`
``` dart
// define by auto-generated file
Future<UserProfile>getMyProfile(Empty empty, {CallOptions opts}) async {
	...
	if (opts != null) {
		opts.headers.forEach((String k, String v) {
			request.headers[k] = v;
		});
	}
	...
}
```
``` dart
// call
var opts = new CallOptions();
opts.setHeader("Authorization", "Bearer ${token}");
var res = service.getMyProfile(new Empty(), opts: opts);
```

I implemented in https://github.com/NoahOrberg/protoc-gen-twirp_dart/tree/n/hotfix/inner-class.
(but, `CallOptions` definition is included auto-generated file, and don't mention this branch name..)

**Comment by matthewtsmith** [comment]
@NoahOrberg This is already possible. The `Default<ServiceName>` method takes a `Requestor`. It is not a required param but if you pass it it allows you to customize the request. A `Requestor` allows you to supply number of `Middleware`. The Middleware gives you hooks for modifying the request before it goes out.

**Comment by n04ln** [comment]
Thanks for your reply.

It worked!

Thank you.
